FROM golang:1.25-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /videobot-worker ./cmd/workers

FROM alpine:3.20

RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=build /videobot-worker ./videobot-worker
COPY configs ./configs

ENTRYPOINT ["./videobot-worker"]
