FROM golang:1.25-alpine AS build

ARG GOOSE_VERSION=v3.24.1
RUN go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.20

RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/goose /usr/local/bin/goose

ENTRYPOINT ["goose"]
